project:
  type: website
  resources:
    - "CNAME"
execute:
  freeze: true

website:
  title: "Jason ZHOU"
  site-url: https://pkuzzq.netlify.app
  description: "A blog for the Bioconductor community!"
  open-graph: true
  navbar:
    right:
      - text: About
        aria-label: "About Me"
        href: about/index.qmd
      - text: Blog
        aria-label: "Meeting People Where They R"
        href: blog/index.qmd
      - text: Talks
        aria-label: "Invited Talks"
        href: talk/index.qmd
      - text: Publications
        aria-label: "Publications"
        href: publication/index.qmd
      - text: Projects
        aria-label: "Project Portfolio"
        href: project/index.qmd
      - icon: rss
format:
  html:
    theme: yeti
    css: styles.css
    include-in-header:
      text: |
        <script defer data-domain="bioconductor.github.io/biocblog" src="https://plausible.io/js/script.js"></script>
