project:
  type: website

execute:
  freeze: true

website:
  title: "Jason ZHOU"
  site-url: https://pkuzzq.netlify.app
  description: "Personal Website"
  open-graph: true
  page-navigation: true
  page-footer:
    border: true
    left: |
      Powered by [Quarto](https://quarto.org).
    center: |
      &copy; 2024 Jason ZHOU. [{{< iconify fa6-regular heart >}} Sponsor](https://github.com/sponsors/mcanouil?o=esb).
    right: |
      License: [CC BY NC SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0).
  navbar:
    pinned: true
    search: true
    background: dark
    foreground: light
    right:
      - text: About
        aria-label: "About Me"
        href: about/index.qmd
      - text: Blog
        aria-label: "Meeting People Where They R"
        href: blog/index.qmd
      - text: Talks
        aria-label: Invited Talks
        href: talk/index.qmd
      - text: Publications
        aria-label: "Publications"
        href: publication/index.qmd
      - text: "Reading"
        aria-label: "Reading"
        href: reading/index.qmd
      - text: "Research"
        href: reading/research.qmd
      - text: Projects
        aria-label: "Project Portfolio"
        href: project/index.qmd
      - icon: github
        href: https://github.com/pkuzzq
      - icon: twitter
        href: https://twitter.com/pkuzzq12345
      - icon: youtube
        href: https://www.youtube.com/@zekiakyol
      - icon: rss
format:
  html:
    theme:
      - coeos
      - custom.scss
    date-format: "dddd[, the] Do [of] MMMM, YYYY"
    email-obfuscation: javascript
    highlight-style: github-dark
    link-external-newwindow: true
    linkcolor: blue
    include-after-body:
      - text: |
          <script type="text/javascript">
          const dateElements = document.querySelectorAll("p.date, div.listing-date");
          dateElements.forEach((el) => {
            el.innerHTML = el.innerHTML.replace(
              /(\d+)(rd|st|th)/g,
              "$1<sup style='font-size:0.5em;font-style:italic;'>$2</sup>"
            );
          });
          </script>
    lightbox: auto
    include-in-header:
      text: |
        <script defer data-domain="bioconductor.github.io/biocblog" src="https://plausible.io/js/script.js"></script>
