project:
  type: website

preview:
  port: 5555
  browser: true
  watch-inputs: true
  navigate: true

execute:
  freeze: true

render:
  - "*.qmd"
  - "*.md"
  - "!etc/"

bibliography: files/bib/references.bib
csl: files/bib/chicago-author-date.csl

# Metadata stuff
pagetitle: "{{< meta title >}} | Jason ZHOU"
author-meta: "Jason ZHOU"

website:
  title: "Jason ZHOU"
  site-url: https://pkuzzq.netlify.app
  description: "Personal Website"
  favicon: "/files/favicon-512.png"

  open-graph: true
  page-navigation: true
  page-footer:
    border: true
    left: |
      Powered by [Quarto](https://quarto.org).
    center: |
      &copy; 2024 Jason ZHOU. [{{< iconify fa6-regular heart >}} Sponsor](https://github.com/sponsors/mcanouil?o=esb).
    right: |
      License: [CC BY NC SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0).
  navbar:
    pinned: true
    search: true
    background: dark
    foreground: light
    left:
      - text: About
        aria-label: "About Me"
        href: about/index.qmd
      - text: "CV"
        href: "cv/index.qmd"
      - text: Blog
        aria-label: "Meeting People Where They R"
        href: blog/index.qmd
      - text: Talks
        aria-label: Invited Talks
        href: talk/index.qmd
      - text: Publications
        aria-label: "Publications"
        href: publication/index.qmd
      - text: "Reading"
        aria-label: "Reading"
        href: reading/index.qmd
      - text: "Research"
        href: research/index.qmd
      - text: Projects
        aria-label: "Project Portfolio"
        href: project/index.qmd

    right:
      - icon: github
        href: https://github.com/pkuzzq
      - icon: twitter
        href: https://twitter.com/pkuzzq12345
      - icon: youtube
        href: https://www.youtube.com/@zekiakyol
      - icon: rss

format:
  html:
    theme:
      - html/ath.scss
    grid:
      body-width: 900px
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai
    date-format: "dddd[, the] Do [of] MMMM, YYYY"
    email-obfuscation: javascript
    link-external-newwindow: true
    include-after-body:
      - text: |
          <script type="text/javascript">
          const dateElements = document.querySelectorAll("p.date, div.listing-date");
          dateElements.forEach((el) => {
            el.innerHTML = el.innerHTML.replace(
              /(\d+)(rd|st|th)/g,
              "$1<sup style='font-size:0.5em;font-style:italic;'>$2</sup>"
            );
          });
          </script>
    lightbox: auto
    include-in-header:
      text: |
        <script defer data-domain="bioconductor.github.io/biocblog" src="https://plausible.io/js/script.js"></script>
